---
- name: master server initial configuration
  hosts: master
  become: yes
  become_user: root
  gather_facts: false
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: ensure git is at the lastest version
      yum:
        name: git
        state: latest

    - name: Docker installation and configuration
      block:
        - name: install Docker from amazon-linux-extras
          command: amazon-linux-extras install -y docker

        - name: start Docker service and enable on machine boot
          service:
            name: docker
            state: started
            enabled: yes

        - name: create 'docker' usergroup
          group:
            name: docker
            state: present

        - name: add ec2-user to docker group so that docker commands can be executed without sudo
          user: 
            name: ec2-user
            group: docker
            append: yes

    - name: install Java JDK (required for Jenkins installation)
      yum: 
        name: java-1.8.0-openjdk-devel

    - name: Jenkins installation and configuration
      block:
        - name: download Jenkins repository using wget
          get_url:
            url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
            dest: /etc/yum.repos.d/jenkins.repo

        - name: import Jenkins key
          rpm_key:
            state: present
            key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

        - name: install Jenkins
          yum:
            name: jenkins
            state: present

        - name: issue daemon_reload to pick up config changes
          systemd: daemon_reload=yes

        - name: start Jenkins and enable during machine boot
          service: 
            name: jenkins
            state: started
            enabled: yes

        - name: delay 30 secs before executing next task (wait for Jenkins to start first)
          wait_for: timeout=30

        - name: get the initial Jenkins admin password 
          command: cat /var/lib/jenkins/secrets/initialAdminPassword 
          changed_when: false
          register: passw

        - name: print the initial Jenkins admin password
          debug:
            var: passw.stdout

        - name: add jenkins-user to docker group to allow jenkins to connect to docker.sock (required for pipeline build docker image)
          user: 
            name: jenkins
            group: docker
            append: yes
        
        # - name: reboot machine (required to adjust changes to user group)
        #   reboot: 